//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RistekPluginSample.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RistekPluginSample.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate beam truss with supports.
        /// </summary>
        internal static string _AutoaddSupportsDesc {
            get {
                return ResourceManager.GetString("_AutoaddSupportsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoset openings count.
        /// </summary>
        internal static string _AutosetTrussParamsInEditModeDesc {
            get {
                return ResourceManager.GetString("_AutosetTrussParamsInEditModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Trusses.
        /// </summary>
        internal static string _beamTrussesFolderNameInBuilding {
            get {
                return ResourceManager.GetString("_beamTrussesFolderNameInBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heel blocking truss.
        /// </summary>
        internal static string _beamTrussKnagaNodeName {
            get {
                return ResourceManager.GetString("_beamTrussKnagaNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Truss wind.
        /// </summary>
        internal static string _beamTrussNodeName {
            get {
                return ResourceManager.GetString("_beamTrussNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension height.
        /// </summary>
        internal static string _DimensionHeight {
            get {
                return ResourceManager.GetString("_DimensionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension length.
        /// </summary>
        internal static string _DimensionLength {
            get {
                return ResourceManager.GetString("_DimensionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is not located above Support.
        /// </summary>
        internal static string _errorMembersNotAboveSupport {
            get {
                return ResourceManager.GetString("_errorMembersNotAboveSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and second Member are not parallel.
        /// </summary>
        internal static string _errorMembersNotParallel {
            get {
                return ResourceManager.GetString("_errorMembersNotParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and second truss cannot be the same.
        /// </summary>
        internal static string _errorSameTruss {
            get {
                return ResourceManager.GetString("_errorSameTruss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and second truss are not parallel.
        /// </summary>
        internal static string _errorTrussesNotParallel {
            get {
                return ResourceManager.GetString("_errorTrussesNotParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect input.
        /// </summary>
        internal static string _IncorrectInput {
            get {
                return ResourceManager.GetString("_IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding vertical heel blocking truss over support mode.
        /// </summary>
        internal static string _KnagaModeDesc {
            get {
                return ResourceManager.GetString("_KnagaModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file: {0}..
        /// </summary>
        internal static string _LoadingFileError {
            get {
                return ResourceManager.GetString("_LoadingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file.\n{0}.
        /// </summary>
        internal static string _LoadingFileError_DocumentSerializer {
            get {
                return ResourceManager.GetString("_LoadingFileError_DocumentSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating beam truss between two selected trusses..
        /// </summary>
        internal static string _MenuToolTip {
            get {
                return ResourceManager.GetString("_MenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom edge distance.
        /// </summary>
        internal static string _OffsetLengwiseBottomDesc {
            get {
                return ResourceManager.GetString("_OffsetLengwiseBottomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top edge distance.
        /// </summary>
        internal static string _OffsetLengwiseTopDesc {
            get {
                return ResourceManager.GetString("_OffsetLengwiseTopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset from plane.
        /// </summary>
        internal static string _OffsetPerpendicularDesc {
            get {
                return ResourceManager.GetString("_OffsetPerpendicularDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outreach beyond perimeter A.
        /// </summary>
        internal static string _OutreachPerpPrimaryDesc {
            get {
                return ResourceManager.GetString("_OutreachPerpPrimaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outreach beyond perimeter B.
        /// </summary>
        internal static string _OutreachPerpSeccondaryDesc {
            get {
                return ResourceManager.GetString("_OutreachPerpSeccondaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plane alignement.
        /// </summary>
        internal static string _PlaneAlignementDesc {
            get {
                return ResourceManager.GetString("_PlaneAlignementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to axis.
        /// </summary>
        internal static string _PlaneAlignementEnum_toAxis {
            get {
                return ResourceManager.GetString("_PlaneAlignementEnum_toAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to bottom / back.
        /// </summary>
        internal static string _PlaneAlignementEnum_toBottom {
            get {
                return ResourceManager.GetString("_PlaneAlignementEnum_toBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to top / front.
        /// </summary>
        internal static string _PlaneAlignementEnum_toTop {
            get {
                return ResourceManager.GetString("_PlaneAlignementEnum_toTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Member in the first truss.
        /// </summary>
        internal static string _preInputs0 {
            get {
                return ResourceManager.GetString("_preInputs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select [option 1] Member in the first truss or [option 2] support.
        /// </summary>
        internal static string _preInputs0_extended {
            get {
                return ResourceManager.GetString("_preInputs0_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Member of Top Chord located above Support in the first truss.
        /// </summary>
        internal static string _preInputs0_knaga {
            get {
                return ResourceManager.GetString("_preInputs0_knaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Member in the second truss.
        /// </summary>
        internal static string _preInputs1 {
            get {
                return ResourceManager.GetString("_preInputs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify new beam truss alignment or press Enter (confirm) or ESC (cancel).
        /// </summary>
        internal static string _preInputs2 {
            get {
                return ResourceManager.GetString("_preInputs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file: {0}..
        /// </summary>
        internal static string _SavingFileError {
            get {
                return ResourceManager.GetString("_SavingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data file..
        /// </summary>
        internal static string _SavingFileError_DocumentSerializer {
            get {
                return ResourceManager.GetString("_SavingFileError_DocumentSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Truss Support 1.
        /// </summary>
        internal static string _Support1 {
            get {
                return ResourceManager.GetString("_Support1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Truss Support 2.
        /// </summary>
        internal static string _Support2 {
            get {
                return ResourceManager.GetString("_Support2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports.
        /// </summary>
        internal static string _supportsFolderName {
            get {
                return ResourceManager.GetString("_supportsFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Truss with simplified input.
        /// </summary>
        internal static string adm_sample_plugin_member {
            get {
                return ResourceManager.GetString("adm_sample_plugin_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment for exist beam.
        /// </summary>
        internal static string alignementForExistBeam {
            get {
                return ResourceManager.GetString("alignementForExistBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment for new beam.
        /// </summary>
        internal static string alignementForNewBeam {
            get {
                return ResourceManager.GetString("alignementForNewBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Along beam.
        /// </summary>
        internal static string alongBeam {
            get {
                return ResourceManager.GetString("alongBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam end extension [mm].
        /// </summary>
        internal static string beamEndExtension {
            get {
                return ResourceManager.GetString("beamEndExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beam height.
        /// </summary>
        internal static string beamHeight {
            get {
                return ResourceManager.GetString("beamHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beam horizontal insertion distance.
        /// </summary>
        internal static string beamHorizontalInsertionDistance {
            get {
                return ResourceManager.GetString("beamHorizontalInsertionDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected beam length.
        /// </summary>
        internal static string beamLength {
            get {
                return ResourceManager.GetString("beamLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beam multiply spacing.
        /// </summary>
        internal static string beamMultiplySpacing {
            get {
                return ResourceManager.GetString("beamMultiplySpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams cannot be collinear. Please choose parallel beam..
        /// </summary>
        internal static string beamsCannotBeCollinear {
            get {
                return ResourceManager.GetString("beamsCannotBeCollinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam start extension [mm].
        /// </summary>
        internal static string beamStartExtension {
            get {
                return ResourceManager.GetString("beamStartExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beam thickness.
        /// </summary>
        internal static string beamThickness {
            get {
                return ResourceManager.GetString("beamThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom plane.
        /// </summary>
        internal static string bottomEdge {
            get {
                return ResourceManager.GetString("bottomEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertToMemberAlignment error for.
        /// </summary>
        internal static string convertToMemberAlignementError {
            get {
                return ResourceManager.GetString("convertToMemberAlignementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance [mm].
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw the beam.
        /// </summary>
        internal static string drawBeam {
            get {
                return ResourceManager.GetString("drawBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        internal static string endPoint {
            get {
                return ResourceManager.GetString("endPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exist beam alignement.
        /// </summary>
        internal static string existBeamAlignement {
            get {
                return ResourceManager.GetString("existBeamAlignement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required fields.
        /// </summary>
        internal static string fillInRequiredFields {
            get {
                return ResourceManager.GetString("fillInRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates beam 1.
        /// </summary>
        internal static string firstSelectedBeamCoordinates {
            get {
                return ResourceManager.GetString("firstSelectedBeamCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have to be larger than zero.
        /// </summary>
        internal static string haveToBeLargerThanZero {
            get {
                return ResourceManager.GetString("haveToBeLargerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal cast.
        /// </summary>
        internal static string horizontalCast {
            get {
                return ResourceManager.GetString("horizontalCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal dimension [mm] .
        /// </summary>
        internal static string horizontalDimension {
            get {
                return ResourceManager.GetString("horizontalDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add beam.
        /// </summary>
        internal static string insert_member_object_plugin {
            get {
                return ResourceManager.GetString("insert_member_object_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a member beetween two exist roof elements..
        /// </summary>
        internal static string insertMemberBeetweenTwoExistRoofElements {
            get {
                return ResourceManager.GetString("insertMemberBeetweenTwoExistRoofElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply beam with spacing.
        /// </summary>
        internal static string multiplyBeamWithSpacing {
            get {
                return ResourceManager.GetString("multiplyBeamWithSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new beam alignement.
        /// </summary>
        internal static string newBeamAlignement {
            get {
                return ResourceManager.GetString("newBeamAlignement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and second point cannot be the same.
        /// </summary>
        internal static string pointsCannotBeTheSame {
            get {
                return ResourceManager.GetString("pointsCannotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the beam.
        /// </summary>
        internal static string rotateBeam {
            get {
                return ResourceManager.GetString("rotateBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates beam 2.
        /// </summary>
        internal static string secondSelectedBeamCoordinates {
            get {
                return ResourceManager.GetString("secondSelectedBeamCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of beam type.
        /// </summary>
        internal static string selectionOfBeamType {
            get {
                return ResourceManager.GetString("selectionOfBeamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the first beam.
        /// </summary>
        internal static string selectTheFirstBeam {
            get {
                return ResourceManager.GetString("selectTheFirstBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the second beam.
        /// </summary>
        internal static string selectTheSecondBeam {
            get {
                return ResourceManager.GetString("selectTheSecondBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set beam dimensions.
        /// </summary>
        internal static string setBeamDimensions {
            get {
                return ResourceManager.GetString("setBeamDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set beam extension.
        /// </summary>
        internal static string setBeamExtension {
            get {
                return ResourceManager.GetString("setBeamExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the beam multiplication.
        /// </summary>
        internal static string setBeamMultiplication {
            get {
                return ResourceManager.GetString("setBeamMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the beam horizontal insertion distance from.
        /// </summary>
        internal static string setHorizontalInsertionFromReferencePart1 {
            get {
                return ResourceManager.GetString("setHorizontalInsertionFromReferencePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference beam start point (to the new beam axis).
        /// </summary>
        internal static string setHorizontalInsertionFromReferencePart2 {
            get {
                return ResourceManager.GetString("setHorizontalInsertionFromReferencePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the rotation relative to the roof slope.
        /// </summary>
        internal static string setRotationRelativeToTheRoofSlope {
            get {
                return ResourceManager.GetString("setRotationRelativeToTheRoofSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point.
        /// </summary>
        internal static string startPoint {
            get {
                return ResourceManager.GetString("startPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Beam.
        /// </summary>
        internal static string steelBeam {
            get {
                return ResourceManager.GetString("steelBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timber Beam.
        /// </summary>
        internal static string timberBeam {
            get {
                return ResourceManager.GetString("timberBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper plane.
        /// </summary>
        internal static string topEdge {
            get {
                return ResourceManager.GetString("topEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown alignement option.
        /// </summary>
        internal static string unknownAlignementOption {
            get {
                return ResourceManager.GetString("unknownAlignementOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation issue.
        /// </summary>
        internal static string validationIssue {
            get {
                return ResourceManager.GetString("validationIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical dimension [mm] .
        /// </summary>
        internal static string verticalDimension {
            get {
                return ResourceManager.GetString("verticalDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be set to 0.
        /// </summary>
        internal static string willBeSetTo0 {
            get {
                return ResourceManager.GetString("willBeSetTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        internal static string wrong {
            get {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input type. Please select timber beam.
        /// </summary>
        internal static string wrongInputType {
            get {
                return ResourceManager.GetString("wrongInputType", resourceCulture);
            }
        }
    }
}
