
rem pre_build_event.bat "SolutionDir" "TargetName"
echo off

rem -------------------------------------------------------------------------

set tmp=%1
set tmp=%tmp:"=%
set SolutionDir=%tmp%
set tmp=

set tmp=%2
set tmp=%tmp:"=%
rem set TargetName=%tmp%
set TargetName="RistekPluginSample"
set tmp=

set DestDir=%SolutionDir%\%TargetName%
set Classname=PreBuildParamsAutogeneratedClass
set TargetFilename=%Classname%".cs"
set ClassFilename=%DestDir%\%TargetFilename%

rem not working propertly when compiling in Poland
rem set DateUsed=%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%
set DateUsed=%DATE%
echo *****
echo ***** Creating file %ClassFilename%
echo *****

rem set Namespace=%TargetName%
set Namespace=RistekPluginSample

echo *****
echo ***** BuildDate = %DateUsed%
echo *****
rem xcopy "%DestDir%\*.*" "%PluginsDir%\" /e /q /y /d /r
rem xcopy "%DestDir%\*.*" "%PluginsDir%\" /e /q /y /d /r /exclude:~~tmp42+~~tmp43+~~tmp44+~~tmp45
rem xcopy "%DestDir%\*.*" "%PluginsDir%\" /e /q /y /d /r /exclude:~~tmp42+~~tmp43+~~tmp44+~~tmp45+~~tmp46+~~tmp47+~~tmp48+~~tmp49+~~tmp50
echo //generated by pre_build_event.bat > %ClassFilename%
echo namespace %Namespace% { public static class %Classname% { public static string BuildDate = "%DateUsed%"; } } >> %ClassFilename%

rem -------------------------------------------------------------------------

goto end

:error_end

set SolutionDir=
set ConfigurationName=
exit /B 1

:end

set SolutionDir=
set ConfigurationName=
